name: Nick
main: com.dusterthefirst.nick.Nick
version: "$$BUILD_NUMBER$$"
api-version: 1.16
api: []
commands:
    reload-config:
        description: Reload the configuration
        usage: /<command>
    whois:
        aliases: [who]
        description: Map nicknames to usernames and vice versa
        usage: /<command> <name>
