name: Nick
main: com.dusterthefirst.nick.Nick
version: "$$BUILD_NUMBER$$"
api-version: 1.16
api: []
commands:
    reload-nicknames:
        description: Reload the nicknames file
        usage: /<command>
